image:
  file: .gitpod.Dockerfile
tasks:
  - name: Run MongoDB 
    init: mkdir -p /workspace/data
    command: mongod --dbpath /workspace/data
  - name: Install MongoDB Database Tools
    init: |
      sudo apt-get install -y mongo-tools 
  - name: Open Workshop instruction document 
    command: gp open mongodb-tutorial.md
ports:
  # MongoDB's port
  - port: 27017
    onOpen: notify
    visibility: public    
vscode:
  extensions:
    - mongodb.mongodb-vscode